StalkBookApplication/StalkBook/Controllers/NewsFeedController.cs
using StalkBook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using StalkBook.Service;

namespace StalkBook.Controllers
{
	[Authorize]
    public class NewsFeedController : Controller
    {
        private NewsfeedService service = new NewsfeedService(null);
        private ProfileService newsFeedService = new ProfileService(null);
        // GET: NewsFeed
        public ActionResult Index()
        {
            var model = service.GetAllAvailableStatuses(User.Identity.GetUserId());
            model.myRatings = service.GetRatingByUserId(User.Identity.GetUserId());


            return View(model);
        }


        [HttpPost]
        public ActionResult Index(Status userStatus)
        {
            string theUserId = User.Identity.GetUserId();
            service.PostStatus(theUserId, userStatus);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RateStatus(int currRating, string arrowDirection, int statusId)
        {
            string theUserId = User.Identity.GetUserId();
            service.UpdateRating(theUserId, currRating, arrowDirection, statusId);

            return new EmptyResult();
        }
    }
}

StalkBookApplication/StalkBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stalkbook</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="~/StyleSheet.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/scripts.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse cssmenu" id="cssmenu">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "NewsFeed")</li>
                    <li>@Html.ActionLink("Profile", "Index", "Profile")</li>
                    <li>@Html.ActionLink("Group", "Index", "Group")</li>
                </ul>
                @*<div class="search-box">
                    <div class="search">
                        <form role="form" method="get" action="~/Search/Search">
                            <input type="search" id="mysearch" placeholder=Search... name="searchString" class="search">
                            <input type="submit" value="Search" class="btn btn-default btn-xs">
                        </form>
                    </div>
                </div>*@
                <div class="col-xs-4 col-md-offset-2 imidju">
                    <form class="navbar-form" role="search" action="~/Search/Search">
                        <div class="input-group">
                            <input type="search" id="mysearch" class="form-control" placeholder="Search..." name="searchString">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div> 


                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - StalkBook LLC.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StalkBookApplication/StalkBook/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stalkbook</title>
    <link rel="stylesheet" type="text/css" href="~/StyleSheet.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <p class="welcome-message"> Welcome to Stalkbook </p>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - StalkBook LLC.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>