StalkBookApplication/StalkBook/Models/GroupViewModel.cs
using StalkBook.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StalkBook.Models
{
    public class GroupViewModel
    {
        public int ID { get; set; }
        public string name { get; set; }
        public DateTime creationDate { get; set; }
        public IEnumerable<Group> groups { get; set; }
        public IEnumerable<int> groupsJoined { get; set; }
        public string searchString { get; set; }
        public string myId { get; set; }
        public int groupId { get; set; }
        public IEnumerable<Status> groupStatuses { get; set; }
        public string body { get; set; }
        public string urlToPic { get; set; }
        public IEnumerable<UserStatusRating> myRatings { get; set; }
        public bool userIsInGroup { get; set; }
        
    }
}

StalkBookApplication/StalkBook/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using StalkBook.Models;
using StalkBook.Service;
using StalkBook.Entity;

namespace StalkBook.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private GroupService service = new GroupService(null);
        private NewsfeedService newsFeedService = new NewsfeedService(null);
        private ProfileService profileService = new ProfileService(null);
        // GET: Group
        public ActionResult Index()
        {
            var model = new GroupViewModel();
            model.groups = service.GetGroupsByUserId(User.Identity.GetUserId());

            return View(model);
        }

        [HttpPost]
        public ActionResult Join(int groupId)
        {
            string theUserId = User.Identity.GetUserId();
            service.AddUserToGroup(theUserId, groupId);

            return new EmptyResult();
        }

        [HttpPost]
        public ActionResult Leave(int groupId)
        {
            string theUserId = User.Identity.GetUserId();
            service.RemoveUserFromGroup(theUserId, groupId);

            return new EmptyResult();
        }

        public ActionResult GetGroupById(int groupId)
        {
            string theUserId = User.Identity.GetUserId();
            var model = service.GetGroupById(groupId, theUserId);
            model.myId = theUserId;
            model.myRatings = newsFeedService.GetRatingByUserId(User.Identity.GetUserId());
           
        

            return View("Group", model);
        }

        public ActionResult Delete(int groupID)
        {
            string theUserId = User.Identity.GetUserId();
            service.DeleteGroup(groupID);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Index(Group groupName)
        {
            if (string.IsNullOrEmpty(groupName.name))
            {
                RedirectToAction("Index");
            }
            else
            {
                string theUserId = User.Identity.GetUserId();
                service.CreateGroup(theUserId, groupName);
            }
            

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult PostStatus(Status status)
        {
            string theUserId = User.Identity.GetUserId();
            service.PostStatus(theUserId, status);

            var model = service.GetGroupById((int)status.groupId, theUserId);
            model.myId = theUserId;
            model.myRatings = newsFeedService.GetRatingByUserId(User.Identity.GetUserId());
            return View("Group", model);
        }

        public ActionResult DeleteStatus(int Id, int groupId)
        {
            profileService.DeleteStatus(Id);      
            string theUserId = User.Identity.GetUserId();
            var model = service.GetGroupById(groupId, theUserId);
            model.myId = theUserId;
            model.myRatings = newsFeedService.GetRatingByUserId(User.Identity.GetUserId());

            return View("Group", model);
        }
    }
}

StalkBookApplication/StalkBook/Controllers/ProfileController.cs
using StalkBook.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using StalkBook.Models;

namespace StalkBook.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
		private ProfileService service = new ProfileService(null);
		private NewsfeedService newsFeedService = new NewsfeedService(null);

		public ActionResult Index()
        {
			var model = service.GetProfile(User.Identity.GetUserId());
            model.myRatings = newsFeedService.GetRatingByUserId(User.Identity.GetUserId());
            model.myId = User.Identity.GetUserId();

            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Index(Status userStatus)
        {
            string theUserId = User.Identity.GetUserId();
            newsFeedService.PostStatus(theUserId, userStatus);

            return RedirectToAction("Index");
        }

		public ActionResult GetProfile(string Id)
		{
			var model = service.GetProfile(Id);
			model.myRatings = newsFeedService.GetRatingByUserId(User.Identity.GetUserId());
			model.myId = User.Identity.GetUserId();

			return View("Index", model);
		}

		public ActionResult DeleteStatus(int Id)
		{
			service.DeleteStatus(Id);

			return RedirectToAction("Index");
		}

		public ActionResult Stalking(string Id)
		{
            var theUserId = User.Identity.GetUserId();
			var model = service.ViewStalking(Id, theUserId);
            model.ElementAt(0).myId = theUserId;
            
			return View("Stalking", model);
		}

		public ActionResult Stalkers(string Id)
		{
            var theUserId = User.Identity.GetUserId();
			var model = service.ViewStalkers(Id, theUserId);
            model.ElementAt(0).myId = theUserId;
            
			return View("Stalking", model);
		}
    }
}

StalkBookApplication/StalkBook/Views/Group/Group.cshtml
@model StalkBook.Models.GroupViewModel

@{
    ViewBag.Title = Model.name;
}

<h2>@Model.name</h2>
@if (Model.userIsInGroup)
{
    <div class="newsfeed-box">
        <form role="form" method="post" action="~/Group/PostStatus">
            <div class="form-group status-content">
                @Html.HiddenFor(model => model.groupId)
                @Html.TextAreaFor(model => model.body, new { @rows = 5, @cols = 50, @maxlength = 200, @placeholder = "What's happening?", htmlAttributes = new { @class = "form-control" } })
                @Html.TextAreaFor(model => model.urlToPic, new { @rows = 1, @cols = 50, @maxlength = 250, @placeholder = "Enter url to picture...", htmlAttributes = new { @class = "form-control" } })
            </div>
            <button type="submit" class="btn btn-default">Post</button>
        </form>
    </div>
}

<div class="all-statuses">
    @foreach (var item in Model.groupStatuses)
    {
        var statusRating = Model.myRatings.Where(s => s.statusId == item.ID).SingleOrDefault();
        var rating = item.upvotes - item.downvotes;
        <div class="content" data-id="@item.ID">
            @if (statusRating == null || statusRating.rating == 0)
            {
                <div class="rating-button neutral-up" role="button" tabindex="0">0</div>
                <div class="rating-button neutral-down" role="button" tabindex="0">0</div>
            }
            else if (statusRating.rating == 1)
            {
                <div class="rating-button upvoted" role="button" tabindex="0">1</div>
                <div class="rating-button neutral-down" role="button" tabindex="0">1</div>
            }
            else
            {
                <div class="rating-button neutral-up" role="button" tabindex="0">2</div>
                <div class="rating-button downvoted" role="button" tabindex="0">2</div>
            }
            <p class="status-rating">@rating</p>
            <div class="status-main">
                <p>@Html.ActionLink(item.fullName, "GetProfile", "Profile", new { Id = item.userId }, null)</p>
                <p>@item.timeCreated.Date.ToShortDateString() @item.timeCreated.ToShortTimeString()</p>
                <p>@item.body</p>
                @if (!String.IsNullOrEmpty(item.urlToPic))
                {
                    <a href="@Url.Content(item.urlToPic)">
                        <img class="status-picture" src="@Url.Content(item.urlToPic)" alt="Image" />
                    </a>
                }
                @if (Model.myId == item.userId)
                {
                    @Html.ActionLink("Delete", "DeleteStatus", "Group", new { Id = item.ID, groupId = item.groupId }, new { @class = "delete-status" })
                }
            </div>

        </div>
    }
</div>

StalkBookApplication/StalkBook/Views/Group/Index.cshtml
@using Antlr.Runtime.Tree
@using Microsoft.AspNet.Identity
@model  StalkBook.Models.GroupViewModel

@{
    ViewBag.Title = "My groups";
}

<div>
    <h2>My Groups</h2>

    <div class="elegant-aero">
        <form role="form" method="post">
            <span class="form-group status-content">
                @Html.TextBoxFor(model => model.name, new { @placeholder = "Enter group name", required = "required", oninvalid="this.setCustomValidity('Enter group name here')", oninput="setCustomValidity('')", maxlength = "35" })
                <button type="submit" class="btn btn-default">Create Group</button>
            </span>

        </form>
    </div>

    <div>
            @foreach (var item in Model.groups)
            {
                if (item.ownerId == User.Identity.GetUserId())
                {
                    <div class="search-body content form-inline">
                        <span>@Html.ActionLink(item.name, "GetGroupById", "Group", new { groupId = item.ID }, null)</span> <span>@Html.ActionLink("Delete group", "Delete", "Group", new { groupID = item.ID }, new { @class = "delete-link" })</span>
                    </div>
                }
                else
                {
                    <p class="search-body content">
                        <span>@Html.ActionLink(item.name, "GetGroupById", "Group", new { groupId = item.ID }, null)</span>
                    </p>
                }
            }
    </div>
</div>

StalkBookApplication/StalkBook/Views/Group/View.cshtml
@model StalkBook.Models.Group

@{
    ViewBag.Title = "View";
}

<h2>View</h2>